### ISSUE TITLE
For IBM Power 64bit operating system, Wizard is not proceeding further when selecting radio bar and clicking button bar

### ISSUE THREAD

**Issue by SriRamaSan** [mlichvar/newt#1]
Environment: Processor: ppc64le, 64 bit, OS: CentOS 7.4, Kernel 3.10, Python version: 3.6.4
Issue description: In the wizard, when user selects the Radio Button (Radio Bar) and clicks on OK/ next button (Button Bar), user is not able to navigate to next screen. 
Analysis of the Issue: The method widget_get_radioValue () is not returning object pointer according to size of 64bit architecture i.e if SIZEOF_VOID_P > SIZEOF_LONG it returns NULL
Recommended fix:
In file snack.c following changes to be made when SIZEOF_VOID_P > SIZEOF_LONG
`static` PyObject * widget_get_radioValue(PyObject *self, void *closure)
{
        snackWidget *w = (snackWidget *)self;
        //return Py_BuildValue("i", newtRadioGetCurrent(w->co));
#if SIZEOF_VOID_P <= SIZEOF_LONG
       return Py_BuildValue("l", (long)newtRadioGetCurrent(w->co));
#else
       return Py_BuildValue("L", (long long)newtRadioGetCurrent(w->co));
#endif
}`

**Comment by mlichvar** [comment]
This issue was reported at https://pagure.io/newt/issue/1. Your code seems similar to what was proposed there, but have not been tested.
